import subprocess

# Pre-approved, parameterized commands. No free-form shell execution.
ALLOWLIST = {
    "open_notepad": {
        "command": ["notepad.exe"],
        "requires_confirmation": False,
        "description": "Open Notepad"
    },
    "open_calculator": {
        "command": ["calc.exe"],
        "requires_confirmation": False,
        "description": "Open Calculator"
    },
    "volume_up": {
        # Using a nirCmd or nircmdc shortcut would be ideal, 
        # but for demonstration we'll just print it.
        "command": ["echo", "Volume Up Simulated"], 
        "requires_confirmation": False,
        "description": "Increase Volume"
    },
    "delete_temp_files": {
        # Extremely dangerous if generated by LLM, safe if hardcoded here
        "command": ["cmd.exe", "/c", "del /q %TEMP%\\*"],
        "requires_confirmation": True,
        "description": "Delete temporary files"
    }
}

def is_allowed(action_name):
    return action_name in ALLOWLIST

def get_action(action_name):
    return ALLOWLIST.get(action_name)

def execute_action(action_name):
    if not is_allowed(action_name):
        raise ValueError(f"Action {action_name} is not in the allowlist.")
        
    action = get_action(action_name)
    try:
        # shell=False prevents shell injection vulnerabilities
        subprocess.Popen(action["command"], shell=False)
        return True, f"Successfully executed: {action['description']}"
    except Exception as e:
        return False, f"Failed to execute {action_name}: {e}"
